---
- name: stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
- name: stop selinux
  selinux:
    state: disabled
- name: time zone set
  shell: "timedatectl set-timezone Asia/Shanghai"